//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilizador", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class Utilizador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoNAVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConcelhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescritivoCodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsGenero GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelemovelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsTipoUtilizador TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UtilizadorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CodigoNAV {
            get {
                return this.CodigoNAVField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoNAVField, value) != true)) {
                    this.CodigoNAVField = value;
                    this.RaisePropertyChanged("CodigoNAV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Concelho {
            get {
                return this.ConcelhoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcelhoField, value) != true)) {
                    this.ConcelhoField = value;
                    this.RaisePropertyChanged("Concelho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DescritivoCodigoPostal {
            get {
                return this.DescritivoCodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.DescritivoCodigoPostalField, value) != true)) {
                    this.DescritivoCodigoPostalField = value;
                    this.RaisePropertyChanged("DescritivoCodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EntityID {
            get {
                return this.EntityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIDField, value) != true)) {
                    this.EntityIDField = value;
                    this.RaisePropertyChanged("EntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsGenero Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((this.GeneroField.Equals(value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Localidade {
            get {
                return this.LocalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadeField, value) != true)) {
                    this.LocalidadeField = value;
                    this.RaisePropertyChanged("Localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Morada {
            get {
                return this.MoradaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoradaField, value) != true)) {
                    this.MoradaField = value;
                    this.RaisePropertyChanged("Morada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NIF {
            get {
                return this.NIFField;
            }
            set {
                if ((object.ReferenceEquals(this.NIFField, value) != true)) {
                    this.NIFField = value;
                    this.RaisePropertyChanged("NIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Telemovel {
            get {
                return this.TelemovelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelemovelField, value) != true)) {
                    this.TelemovelField = value;
                    this.RaisePropertyChanged("Telemovel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsTipoUtilizador Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal long UtilizadorID {
            get {
                return this.UtilizadorIDField;
            }
            set {
                if ((this.UtilizadorIDField.Equals(value) != true)) {
                    this.UtilizadorIDField = value;
                    this.RaisePropertyChanged("UtilizadorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.Genero", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Utils")]
    internal enum EnumsGenero : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feminino = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.TipoUtilizador", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Utils")]
    internal enum EnumsTipoUtilizador : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoAutenticado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GestorConteudo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medico = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Utente = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APTempoEspera", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class APTempoEspera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EncerradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutosEsperaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsTipoAtendimentoPermanente TipoAtendimentoPermanenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Encerrado {
            get {
                return this.EncerradoField;
            }
            set {
                if ((this.EncerradoField.Equals(value) != true)) {
                    this.EncerradoField = value;
                    this.RaisePropertyChanged("Encerrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int MinutosEspera {
            get {
                return this.MinutosEsperaField;
            }
            set {
                if ((this.MinutosEsperaField.Equals(value) != true)) {
                    this.MinutosEsperaField = value;
                    this.RaisePropertyChanged("MinutosEspera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.EnumsTipoAtendimentoPermanente TipoAtendimentoPermanente {
            get {
                return this.TipoAtendimentoPermanenteField;
            }
            set {
                if ((this.TipoAtendimentoPermanenteField.Equals(value) != true)) {
                    this.TipoAtendimentoPermanenteField = value;
                    this.RaisePropertyChanged("TipoAtendimentoPermanente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.TipoAtendimentoPermanente", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Utils")]
    internal enum EnumsTipoAtendimentoPermanente : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CentroClinicoAdultos = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CentroClinicoPediatria = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HospitalAdultos = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HospitalPediatria = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HomepageBanner", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class HomepageBanner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NovaJanelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Imagem {
            get {
                return this.ImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemField, value) != true)) {
                    this.ImagemField = value;
                    this.RaisePropertyChanged("Imagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool NovaJanela {
            get {
                return this.NovaJanelaField;
            }
            set {
                if ((this.NovaJanelaField.Equals(value) != true)) {
                    this.NovaJanelaField = value;
                    this.RaisePropertyChanged("NovaJanela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadeSaude", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class UnidadeSaude : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUnidadeSaudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoordenadasGPSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUnidadeSaudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CodigoUnidadeSaude {
            get {
                return this.CodigoUnidadeSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUnidadeSaudeField, value) != true)) {
                    this.CodigoUnidadeSaudeField = value;
                    this.RaisePropertyChanged("CodigoUnidadeSaude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CoordenadasGPS {
            get {
                return this.CoordenadasGPSField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordenadasGPSField, value) != true)) {
                    this.CoordenadasGPSField = value;
                    this.RaisePropertyChanged("CoordenadasGPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdUnidadeSaude {
            get {
                return this.IdUnidadeSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUnidadeSaudeField, value) != true)) {
                    this.IdUnidadeSaudeField = value;
                    this.RaisePropertyChanged("IdUnidadeSaude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ImagemMobile {
            get {
                return this.ImagemMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemMobileField, value) != true)) {
                    this.ImagemMobileField = value;
                    this.RaisePropertyChanged("ImagemMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Morada {
            get {
                return this.MoradaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoradaField, value) != true)) {
                    this.MoradaField = value;
                    this.RaisePropertyChanged("Morada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NumeroTelefone {
            get {
                return this.NumeroTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTelefoneField, value) != true)) {
                    this.NumeroTelefoneField = value;
                    this.RaisePropertyChanged("NumeroTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noticia", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class Noticia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNoticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoDescritivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlNoticiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdNoticia {
            get {
                return this.IdNoticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNoticiaField, value) != true)) {
                    this.IdNoticiaField = value;
                    this.RaisePropertyChanged("IdNoticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ImagemMobile {
            get {
                return this.ImagemMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemMobileField, value) != true)) {
                    this.ImagemMobileField = value;
                    this.RaisePropertyChanged("ImagemMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TextoDescritivo {
            get {
                return this.TextoDescritivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoDescritivoField, value) != true)) {
                    this.TextoDescritivoField = value;
                    this.RaisePropertyChanged("TextoDescritivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UrlNoticia {
            get {
                return this.UrlNoticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlNoticiaField, value) != true)) {
                    this.UrlNoticiaField = value;
                    this.RaisePropertyChanged("UrlNoticia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class Consulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MomentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeSaudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Acto {
            get {
                return this.ActoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActoField, value) != true)) {
                    this.ActoField = value;
                    this.RaisePropertyChanged("Acto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdConsulta {
            get {
                return this.IdConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdConsultaField, value) != true)) {
                    this.IdConsultaField = value;
                    this.RaisePropertyChanged("IdConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Momento {
            get {
                return this.MomentoField;
            }
            set {
                if ((this.MomentoField.Equals(value) != true)) {
                    this.MomentoField = value;
                    this.RaisePropertyChanged("Momento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UnidadeSaude {
            get {
                return this.UnidadeSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeSaudeField, value) != true)) {
                    this.UnidadeSaudeField = value;
                    this.RaisePropertyChanged("UnidadeSaude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosAgendamento", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class DadosAgendamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] DoctorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] FacilitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DadosAgendamento.Relation[] RelationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.ServiceItem[] ServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] SpecialtiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] Doctors {
            get {
                return this.DoctorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorsField, value) != true)) {
                    this.DoctorsField = value;
                    this.RaisePropertyChanged("Doctors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] Facilities {
            get {
                return this.FacilitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacilitiesField, value) != true)) {
                    this.FacilitiesField = value;
                    this.RaisePropertyChanged("Facilities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DadosAgendamento.Relation[] Relations {
            get {
                return this.RelationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationsField, value) != true)) {
                    this.RelationsField = value;
                    this.RaisePropertyChanged("Relations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.ServiceItem[] Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] Specialties {
            get {
                return this.SpecialtiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialtiesField, value) != true)) {
                    this.SpecialtiesField = value;
                    this.RaisePropertyChanged("Specialties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem[] Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="DadosAgendamento.Relation", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
        [System.SerializableAttribute()]
        internal partial class Relation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DoctorIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FacilityIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ServiceIDField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string SpecialtyIDField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            internal string DoctorID {
                get {
                    return this.DoctorIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.DoctorIDField, value) != true)) {
                        this.DoctorIDField = value;
                        this.RaisePropertyChanged("DoctorID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            internal string FacilityID {
                get {
                    return this.FacilityIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.FacilityIDField, value) != true)) {
                        this.FacilityIDField = value;
                        this.RaisePropertyChanged("FacilityID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            internal string ServiceID {
                get {
                    return this.ServiceIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.ServiceIDField, value) != true)) {
                        this.ServiceIDField = value;
                        this.RaisePropertyChanged("ServiceID");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            internal string SpecialtyID {
                get {
                    return this.SpecialtyIDField;
                }
                set {
                    if ((object.ReferenceEquals(this.SpecialtyIDField, value) != true)) {
                        this.SpecialtyIDField = value;
                        this.RaisePropertyChanged("SpecialtyID");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataItem", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.ServiceItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataHoraAgendamentoItem))]
    internal partial class DataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Designacao {
            get {
                return this.DesignacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignacaoField, value) != true)) {
                    this.DesignacaoField = value;
                    this.RaisePropertyChanged("Designacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceItem", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class ServiceItem : SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataHoraAgendamentoItem", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class DataHoraAgendamentoItem : SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignacaoRecursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRecursoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DesignacaoRecurso {
            get {
                return this.DesignacaoRecursoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignacaoRecursoField, value) != true)) {
                    this.DesignacaoRecursoField = value;
                    this.RaisePropertyChanged("DesignacaoRecurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdRecurso {
            get {
                return this.IdRecursoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRecursoField, value) != true)) {
                    this.IdRecursoField = value;
                    this.RaisePropertyChanged("IdRecurso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganismoPlano", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class OrganismoPlano : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string InsuranceDesc {
            get {
                return this.InsuranceDescField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceDescField, value) != true)) {
                    this.InsuranceDescField = value;
                    this.RaisePropertyChanged("InsuranceDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string InsuranceID {
            get {
                return this.InsuranceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceIDField, value) != true)) {
                    this.InsuranceIDField = value;
                    this.RaisePropertyChanged("InsuranceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PlanDesc {
            get {
                return this.PlanDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanDescField, value) != true)) {
                    this.PlanDescField = value;
                    this.RaisePropertyChanged("PlanDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PlanID {
            get {
                return this.PlanIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanIDField, value) != true)) {
                    this.PlanIDField = value;
                    this.RaisePropertyChanged("PlanID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoFinanceiro", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class DocumentoFinanceiro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeSaudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Acto {
            get {
                return this.ActoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActoField, value) != true)) {
                    this.ActoField = value;
                    this.RaisePropertyChanged("Acto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDocumentoField, value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((this.PagoField.Equals(value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UnidadeSaude {
            get {
                return this.UnidadeSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeSaudeField, value) != true)) {
                    this.UnidadeSaudeField = value;
                    this.RaisePropertyChanged("UnidadeSaude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeclaracaoPresenca", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class DeclaracaoPresenca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDeclaracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MomentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeSaudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Acto {
            get {
                return this.ActoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActoField, value) != true)) {
                    this.ActoField = value;
                    this.RaisePropertyChanged("Acto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IdDeclaracao {
            get {
                return this.IdDeclaracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDeclaracaoField, value) != true)) {
                    this.IdDeclaracaoField = value;
                    this.RaisePropertyChanged("IdDeclaracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Momento {
            get {
                return this.MomentoField;
            }
            set {
                if ((this.MomentoField.Equals(value) != true)) {
                    this.MomentoField = value;
                    this.RaisePropertyChanged("Momento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UnidadeSaude {
            get {
                return this.UnidadeSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeSaudeField, value) != true)) {
                    this.UnidadeSaudeField = value;
                    this.RaisePropertyChanged("UnidadeSaude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Senha", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class Senha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GabineteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MomentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaEsperaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gabinete {
            get {
                return this.GabineteField;
            }
            set {
                if ((object.ReferenceEquals(this.GabineteField, value) != true)) {
                    this.GabineteField = value;
                    this.RaisePropertyChanged("Gabinete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Momento {
            get {
                return this.MomentoField;
            }
            set {
                if ((this.MomentoField.Equals(value) != true)) {
                    this.MomentoField = value;
                    this.RaisePropertyChanged("Momento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RowID {
            get {
                return this.RowIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RowIDField, value) != true)) {
                    this.RowIDField = value;
                    this.RaisePropertyChanged("RowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SalaEspera {
            get {
                return this.SalaEsperaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaEsperaField, value) != true)) {
                    this.SalaEsperaField = value;
                    this.RaisePropertyChanged("SalaEspera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensagemAssunto", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class MensagemAssunto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignacaoAssuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MensagemAssuntoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DesignacaoAssunto {
            get {
                return this.DesignacaoAssuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignacaoAssuntoField, value) != true)) {
                    this.DesignacaoAssuntoField = value;
                    this.RaisePropertyChanged("DesignacaoAssunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal long MensagemAssuntoID {
            get {
                return this.MensagemAssuntoIDField;
            }
            set {
                if ((this.MensagemAssuntoIDField.Equals(value) != true)) {
                    this.MensagemAssuntoIDField = value;
                    this.RaisePropertyChanged("MensagemAssuntoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensagem", Namespace="http://schemas.datacontract.org/2004/07/MySAMSApi.Regras.Models")]
    [System.SerializableAttribute()]
    internal partial class Mensagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AnexosNomesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ConversacaoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailRemetenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MensagemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MensagemRecebidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeRemetenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TemAnexosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoMensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VistoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string[] AnexosNomes {
            get {
                return this.AnexosNomesField;
            }
            set {
                if ((object.ReferenceEquals(this.AnexosNomesField, value) != true)) {
                    this.AnexosNomesField = value;
                    this.RaisePropertyChanged("AnexosNomes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Assunto {
            get {
                return this.AssuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssuntoField, value) != true)) {
                    this.AssuntoField = value;
                    this.RaisePropertyChanged("Assunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> ConversacaoID {
            get {
                return this.ConversacaoIDField;
            }
            set {
                if ((this.ConversacaoIDField.Equals(value) != true)) {
                    this.ConversacaoIDField = value;
                    this.RaisePropertyChanged("ConversacaoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EmailDestinatario {
            get {
                return this.EmailDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailDestinatarioField, value) != true)) {
                    this.EmailDestinatarioField = value;
                    this.RaisePropertyChanged("EmailDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EmailRemetente {
            get {
                return this.EmailRemetenteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailRemetenteField, value) != true)) {
                    this.EmailRemetenteField = value;
                    this.RaisePropertyChanged("EmailRemetente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal long MensagemID {
            get {
                return this.MensagemIDField;
            }
            set {
                if ((this.MensagemIDField.Equals(value) != true)) {
                    this.MensagemIDField = value;
                    this.RaisePropertyChanged("MensagemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool MensagemRecebida {
            get {
                return this.MensagemRecebidaField;
            }
            set {
                if ((this.MensagemRecebidaField.Equals(value) != true)) {
                    this.MensagemRecebidaField = value;
                    this.RaisePropertyChanged("MensagemRecebida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NomeDestinatario {
            get {
                return this.NomeDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeDestinatarioField, value) != true)) {
                    this.NomeDestinatarioField = value;
                    this.RaisePropertyChanged("NomeDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NomeRemetente {
            get {
                return this.NomeRemetenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeRemetenteField, value) != true)) {
                    this.NomeRemetenteField = value;
                    this.RaisePropertyChanged("NomeRemetente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool TemAnexos {
            get {
                return this.TemAnexosField;
            }
            set {
                if ((this.TemAnexosField.Equals(value) != true)) {
                    this.TemAnexosField = value;
                    this.RaisePropertyChanged("TemAnexos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TextoMensagem {
            get {
                return this.TextoMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoMensagemField, value) != true)) {
                    this.TextoMensagemField = value;
                    this.RaisePropertyChanged("TextoMensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Visto {
            get {
                return this.VistoField;
            }
            set {
                if ((this.VistoField.Equals(value) != true)) {
                    this.VistoField = value;
                    this.RaisePropertyChanged("Visto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySAMSApiWS.IMySAMSApiWS")]
    internal interface IMySAMSApiWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/Login", ReplyAction="http://tempuri.org/IMySAMSApiWS/LoginResponse")]
        bool Login(string beneficiario, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/AlterarPin", ReplyAction="http://tempuri.org/IMySAMSApiWS/AlterarPinResponse")]
        bool AlterarPin(out string errorMessage, string nAplicacional, string pinAnterior, string pinNovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterDadosPessoais", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterDadosPessoaisResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Utilizador ObterDadosPessoais(string beneficiario, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/AtualizarDadosPessoais", ReplyAction="http://tempuri.org/IMySAMSApiWS/AtualizarDadosPessoaisResponse")]
        bool AtualizarDadosPessoais(string beneficiario, string pin, string Telefone, string Telemovel, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterTempoAP", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterTempoAPResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.APTempoEspera[] ObterTempoAP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterBannersHomepage", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterBannersHomepageResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.HomepageBanner[] ObterBannersHomepage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaUnidades", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaUnidadesResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.UnidadeSaude[] ObterListaUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaNoticias", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaNoticiasResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Noticia[] ObterListaNoticias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaConsultas", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaConsultasResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Consulta[] ObterListaConsultas(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/CancelarAgendamento", ReplyAction="http://tempuri.org/IMySAMSApiWS/CancelarAgendamentoResponse")]
        bool CancelarAgendamento(string beneficiario, string agendamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterDadosAgendamento", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterDadosAgendamentoResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DadosAgendamento ObterDadosAgendamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterDatasDisponiveisAgendamento", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterDatasDisponiveisAgendamentoResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataHoraAgendamentoItem[] ObterDatasDisponiveisAgendamento(string beneficiario, string hospital, string especialidade, string recurso, string servico, string inicio, string entidade, string plano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterHorasDisponiveisAgendamento", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterHorasDisponiveisAgendamentoResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataHoraAgendamentoItem[] ObterHorasDisponiveisAgendamento(string beneficiario, string hospital, string especialidade, string recurso, string servico, string data, string entidade, string plano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterEntidadesAgendamento", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterEntidadesAgendamentoResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.OrganismoPlano[] ObterEntidadesAgendamento(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/Agendar", ReplyAction="http://tempuri.org/IMySAMSApiWS/AgendarResponse")]
        bool Agendar(string beneficiario, string slot, string servico, string organismo, string plano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaDocumentos", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaDocumentosResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DocumentoFinanceiro[] ObterListaDocumentos(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/DevolverDocumento", ReplyAction="http://tempuri.org/IMySAMSApiWS/DevolverDocumentoResponse")]
        byte[] DevolverDocumento(string beneficiario, string idDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaDeclaracoesPresenca", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaDeclaracoesPresencaResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DeclaracaoPresenca[] ObterListaDeclaracoesPresenca(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/DevolverDeclaracaoPresenca", ReplyAction="http://tempuri.org/IMySAMSApiWS/DevolverDeclaracaoPresencaResponse")]
        byte[] DevolverDeclaracaoPresenca(string beneficiario, string idDeclaracao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/CheckIn", ReplyAction="http://tempuri.org/IMySAMSApiWS/CheckInResponse")]
        int CheckIn(string beneficiario, string rowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterPrevisaoAtendimento", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterPrevisaoAtendimentoResponse")]
        int ObterPrevisaoAtendimento(string beneficiario, string rowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/AvaliarAtendimento", ReplyAction="http://tempuri.org/IMySAMSApiWS/AvaliarAtendimentoResponse")]
        bool AvaliarAtendimento(string beneficiario, string rowId, int avaliacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterSenhas", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterSenhasResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Senha[] ObterSenhas(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterQRCode", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterQRCodeResponse")]
        byte[] ObterQRCode(string beneficiario, string rowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaAssuntos", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaAssuntosResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.MensagemAssunto[] ObterListaAssuntos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaDestinatarios", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaDestinatariosResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Utilizador[] ObterListaDestinatarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ObterListaMensagens", ReplyAction="http://tempuri.org/IMySAMSApiWS/ObterListaMensagensResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Mensagem[] ObterListaMensagens(string beneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/AbrirMensagem", ReplyAction="http://tempuri.org/IMySAMSApiWS/AbrirMensagemResponse")]
        SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Mensagem[] AbrirMensagem(string beneficiario, long mensagemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/AbrirAnexo", ReplyAction="http://tempuri.org/IMySAMSApiWS/AbrirAnexoResponse")]
        byte[] AbrirAnexo(long mensagemId, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/ResponderMensagem", ReplyAction="http://tempuri.org/IMySAMSApiWS/ResponderMensagemResponse")]
        long ResponderMensagem(string beneficiario, long mensagemId, string textoMensagem, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySAMSApiWS/CriarMensagem", ReplyAction="http://tempuri.org/IMySAMSApiWS/CriarMensagemResponse")]
        long CriarMensagem(string beneficiario, long destinatarioId, long assuntoId, string textoMensagem, string[] anexos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IMySAMSApiWSChannel : SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.IMySAMSApiWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MySAMSApiWSClient : System.ServiceModel.ClientBase<SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.IMySAMSApiWS>, SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.IMySAMSApiWS {
        
        public MySAMSApiWSClient() {
        }
        
        public MySAMSApiWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySAMSApiWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySAMSApiWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySAMSApiWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string beneficiario, string pin) {
            return base.Channel.Login(beneficiario, pin);
        }
        
        public bool AlterarPin(out string errorMessage, string nAplicacional, string pinAnterior, string pinNovo) {
            return base.Channel.AlterarPin(out errorMessage, nAplicacional, pinAnterior, pinNovo);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Utilizador ObterDadosPessoais(string beneficiario, string pin) {
            return base.Channel.ObterDadosPessoais(beneficiario, pin);
        }
        
        public bool AtualizarDadosPessoais(string beneficiario, string pin, string Telefone, string Telemovel, string Email) {
            return base.Channel.AtualizarDadosPessoais(beneficiario, pin, Telefone, Telemovel, Email);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.APTempoEspera[] ObterTempoAP() {
            return base.Channel.ObterTempoAP();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.HomepageBanner[] ObterBannersHomepage() {
            return base.Channel.ObterBannersHomepage();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.UnidadeSaude[] ObterListaUnidades() {
            return base.Channel.ObterListaUnidades();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Noticia[] ObterListaNoticias() {
            return base.Channel.ObterListaNoticias();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Consulta[] ObterListaConsultas(string beneficiario) {
            return base.Channel.ObterListaConsultas(beneficiario);
        }
        
        public bool CancelarAgendamento(string beneficiario, string agendamento) {
            return base.Channel.CancelarAgendamento(beneficiario, agendamento);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DadosAgendamento ObterDadosAgendamento() {
            return base.Channel.ObterDadosAgendamento();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataHoraAgendamentoItem[] ObterDatasDisponiveisAgendamento(string beneficiario, string hospital, string especialidade, string recurso, string servico, string inicio, string entidade, string plano) {
            return base.Channel.ObterDatasDisponiveisAgendamento(beneficiario, hospital, especialidade, recurso, servico, inicio, entidade, plano);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DataHoraAgendamentoItem[] ObterHorasDisponiveisAgendamento(string beneficiario, string hospital, string especialidade, string recurso, string servico, string data, string entidade, string plano) {
            return base.Channel.ObterHorasDisponiveisAgendamento(beneficiario, hospital, especialidade, recurso, servico, data, entidade, plano);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.OrganismoPlano[] ObterEntidadesAgendamento(string beneficiario) {
            return base.Channel.ObterEntidadesAgendamento(beneficiario);
        }
        
        public bool Agendar(string beneficiario, string slot, string servico, string organismo, string plano) {
            return base.Channel.Agendar(beneficiario, slot, servico, organismo, plano);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DocumentoFinanceiro[] ObterListaDocumentos(string beneficiario) {
            return base.Channel.ObterListaDocumentos(beneficiario);
        }
        
        public byte[] DevolverDocumento(string beneficiario, string idDocumento) {
            return base.Channel.DevolverDocumento(beneficiario, idDocumento);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.DeclaracaoPresenca[] ObterListaDeclaracoesPresenca(string beneficiario) {
            return base.Channel.ObterListaDeclaracoesPresenca(beneficiario);
        }
        
        public byte[] DevolverDeclaracaoPresenca(string beneficiario, string idDeclaracao) {
            return base.Channel.DevolverDeclaracaoPresenca(beneficiario, idDeclaracao);
        }
        
        public int CheckIn(string beneficiario, string rowId) {
            return base.Channel.CheckIn(beneficiario, rowId);
        }
        
        public int ObterPrevisaoAtendimento(string beneficiario, string rowId) {
            return base.Channel.ObterPrevisaoAtendimento(beneficiario, rowId);
        }
        
        public bool AvaliarAtendimento(string beneficiario, string rowId, int avaliacao) {
            return base.Channel.AvaliarAtendimento(beneficiario, rowId, avaliacao);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Senha[] ObterSenhas(string beneficiario) {
            return base.Channel.ObterSenhas(beneficiario);
        }
        
        public byte[] ObterQRCode(string beneficiario, string rowID) {
            return base.Channel.ObterQRCode(beneficiario, rowID);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.MensagemAssunto[] ObterListaAssuntos() {
            return base.Channel.ObterListaAssuntos();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Utilizador[] ObterListaDestinatarios() {
            return base.Channel.ObterListaDestinatarios();
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Mensagem[] ObterListaMensagens(string beneficiario) {
            return base.Channel.ObterListaMensagens(beneficiario);
        }
        
        public SS.HealthApp.ClientConnector.SAMS.MySAMSApiWS.Mensagem[] AbrirMensagem(string beneficiario, long mensagemId) {
            return base.Channel.AbrirMensagem(beneficiario, mensagemId);
        }
        
        public byte[] AbrirAnexo(long mensagemId, string nome) {
            return base.Channel.AbrirAnexo(mensagemId, nome);
        }
        
        public long ResponderMensagem(string beneficiario, long mensagemId, string textoMensagem, string[] anexos) {
            return base.Channel.ResponderMensagem(beneficiario, mensagemId, textoMensagem, anexos);
        }
        
        public long CriarMensagem(string beneficiario, long destinatarioId, long assuntoId, string textoMensagem, string[] anexos) {
            return base.Channel.CriarMensagem(beneficiario, destinatarioId, assuntoId, textoMensagem, anexos);
        }
    }
}
