//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.HealthApp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorLogID { get; set; }
        public short Priority { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
        public System.DateTime Moment { get; set; }
        public string CompanyID { get; set; }
        public string UserID { get; set; }
    }
}
